use_frameworks!

def shared_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # ignore all warnings from all pods
  inhibit_all_warnings!

   pod 'UDWrapper', :path => '../'

end

target 'UDWrapper_Example' do
  use_frameworks!

  shared_pods

  target 'UDWrapper_Tests' do
    inherit! :search_paths

    shared_pods
    
  end
end
